apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: main-api
  name: main-api
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 80
  selector:
    io.kompose.service: main-api
status:
  loadBalancer: {}
