apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: profanity-api
  name: profanity-api
spec:
  ports:
  - name: "3020"
    port: 3020
    targetPort: 3000
  selector:
    io.kompose.service: profanity-api
status:
  loadBalancer: {}
