apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq-server
  name: rabbitmq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq-server
    spec:
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: ""
        name: rabbitmq-server
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      hostname: rabbitserver
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
