apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sentiment-api
  name: sentiment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sentiment-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sentiment-api
    spec:
      containers:
      - env:
        - name: IDENTITY_AUTHORITY
        image: jodaniel1409/sentiment-api
        imagePullPolicy: ""
        name: sentiment-api
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
